### ISSUE TITLE
ILM section could use some rewording

### ISSUE THREAD

**Issue by johnlantz** [NetAppDocs/bluexp-tiering#44]
### Page URL

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-gcp.html

### Page title

Tiering data from on-premises ONTAP clusters to Google Cloud Storage

### Summary

The ILM section (5b: Storage Class Life Cycle) could use some rewording.

1. Lifecycle is one word.
2. Repeated use of the word “move” is inaccurate. Objects never move out of the bucket. Storage classes are applied to objects. Nothing “moves”. Storage classes are "applied" to objects.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi John,  Thanks for your feedback.  I'll make these updates shortly.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi John, Thanks again.  I am closing this issue now.

Thanks, Tom
