### ISSUE TITLE
Deploying CVO and/or GCP Buckets in a "Supported Region"

### ISSUE THREAD

**Issue by tristenwi** [NetAppDocs/bluexp-tiering#49]
### Page URL

https://docs.netapp.com/us-en/bluexp-tiering/reference-google-support.html

### Page title

Supported Google Cloud storage classes and regions

### Summary

Hello! 

Regarding BlueXP Cloud Tiering (GCP) for a CVO cluster....the documentation states, 
"BlueXP tiering supports the following regions." (Then the regions are listed below.) 

Does this mean... 
Just the CVO clusters needs to be deployed in a supported region?
The GCP Bucket needs to be deployed in a supported region?
Or...both the CVO and the GCP Bucket needs to be deployed in a supported region? 

Looking for additional details or clarity. Thank you!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi [tristenwi](https://github.com/tristenwi),  The BlueXP tiering service is for on-prem ONTAP systems only, so the references to supported regions is for the GCP bucket.  There is tiering for CVOs as well, but that is not controlled by the BlueXP tiering service, it is just a capability that you can set on CVO volumes.

Does that answer your question?

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Tristen,  I guess it could be clarified for users who are not familiar with the tiering service, or if users access this page from a search in general about tiering, so I can make a change to this page (plus the AWS and Azure pages) to mention on-prem systems.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
The sentence now reads "When you set up data tiering to GCP **from your on-premises ONTAP systems**, ...".    

Thanks Tom

**Comment by tristenwi** [comment]
I appreciate the update and adjustment, thank you Tom! I see the change.
