### ISSUE TITLE
Missing description of S3 CMEK encryption with AWS KMS

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/bluexp-tiering#53]
### Page URL

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html

### Page title

Tiering data from on-premises ONTAP clusters to Amazon S3

### Summary

Hi,
Missing here a section for S3 encryption with AWS KMS customer managed keys as explained for Tiering with CVO: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-setting-up-kms.html
Thx
Holger

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Thanks @kholger. We'll take a look and let you know if there are any questions.

**Comment by netapp-bcammett** [comment]
The AWS KMS isn't supported with on-prem ONTAP clusters.
