### ISSUE TITLE
Update the page to indicate that this is UI only and no email will be sent for this notification.

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/bluexp-tiering#55]
### Page URL

https://docs.netapp.com/us-en/bluexp-tiering/task-monitor-tiering-alerts.html

### Page title

Monitor the status of tiering alerts

### Summary

Please update the page to indicate that this notification will not generate an email.

See the following as an example of how we document UI only versus Email.
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@binder1234,

Thanks for reaching out. According to [this page](https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#set-email-notification-settings), email notifications can be set up for BlueXP tiering:

> At this time, notifications are sent by email for the following BlueXP features and services: Connector, BlueXP digital wallet, BlueXP copy and sync, BlueXP backup and recovery, and BlueXP tiering. Additional services will be added in future releases.

Have you experienced otherwise?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
@binder1234, I wanted to follow up on my previous question. I believe email notifications can be set up for BlueXP tiering. Is that not working for you?

**Comment by netapp-bcammett** [comment]
I updated the page to note that BlueXP doesn't send an email for this notification.

Thanks,
Ben
